---
- hosts: router
  become: yes

  tasks:
    
    - name: Create Loopback111
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback111
            description: Created by ansible
            enabled: true

    - name: Set loopback IPv4 address
      cisco.ios.ios_l3_interface:
        name: Loopback111
        ipv4: 4.4.4.4/24


    - name: Set Gigabitethernet0/2 ipv4 address
      cisco.ios.ios_l3_interface:
        name: GigabitEthernet0/2
        ipv4: 192.168.122.205/24

    - name: Set GigabitEthernet0/3 IPv4 address
      cisco.ios.ios_l3_interface:
        name: GigabitEthernet0/3
        ipv4: 192.168.122.206/24


#ansible-playbook cisco.yml -i hosts.yml
#become means we use enable